### PR TITLE
chore(notebook):  copy configs files from Google Drive

### LINKED ISSUE #1063: Add option for copying over Google Drive configs file to colab
### Is your feature request related to a problem? Please describe.

I'm always frustrated when I have to manually copy over the configs file from Google Drive to Colab

### Describe alternatives you've considered

I manually edited the code every time because it was faster but it would be more helpful if it was built in

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Are you willing to resolve this issue by submitting a Pull Request?

- [X] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

### PR DESCRIPTION
**Pull request by Onako2**
Changes:
- Added "import" for configs files
- Added backing up of the config file if you accidentaly override it
- Changed "clone" to export for configs files

### Description of change

Made that you can also import the configs files from Google Drive because it takes long if you have to do it every time to copy paste the files.

The Pull Request Fixes #1063

### Pull-Request Checklist

- [x] Code is up-to-date with the `main` branch
- [x] This pull request follows [Contributing.md](https://github.com/34j/so-vits-svc-fork/blob/main/CONTRIBUTING.md)
- [x] This pull request links relevant issues as `Fixes #1063`
- [ ] `pre-commit run -a` passes with this change or ci passes
- [ ] `poetry run pytest` passes with this change or ci passes
- [ ] (There are new or updated unit tests validating the change)
- [ ] Documentation has been updated to reflect this change
- [ ] The new commits follow conventions outlined in the [conventional commit spec](https://www.conventionalcommits.org/en/v1.0.0/)

### CODE REVIEW

**Comment by Onako2** [comment]
` CI / Lint Commit Messages (pull_request)`  
Does somebody know how to fix that?

**Comment by 34j** [comment]
Thanks for your suggestion. It would be nice to have an error handling and an explanation that this operation is optional to avoid confusion.

**Comment by Onako2** [comment]
> Thanks for your suggestion. It would be nice to have an error handling and an explanation that this operation is optional to avoid confusion.

Ok, I'll do it when I am home

**Comment by Onako2** [comment]
> Thanks for your suggestion. It would be nice to have an error handling and an explanation that this operation is optional to avoid confusion.

How do you mean error handling?

**Comment by 34j** [comment]
@allcontributors add Onako2 docs

**Pull request merged**
